# Generated by Django 4.2b1 on 2023-08-01 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_question_is_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='customer_app.question'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question',)},
        ),
    ]
