# Generated by Django 4.2b1 on 2023-07-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_app', '0002_notice_viewcnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notice_files/'),
        ),
    ]
