# Generated by Django 4.2.7 on 2023-11-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_app', '0003_alter_notice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
