# Generated by Django 4.2b1 on 2023-07-25 05:55

from django.db import migrations
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', index.models.CustomUserManager()),
            ],
        ),
    ]
