# Generated by Django 4.2.7 on 2023-11-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
