# Generated by Django 4.2.7 on 2023-11-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
    ]
